" Name:         Met Office
" Description:  Met Office branded colour scheme
" Author:       Violet Sherratt <violet.sherratt@metoffice.gov.uk>
" Maintainer:   Violet Sherratt <violet.sherratt@metoffice.gov.uk>
" License:      Public domain

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'metoffice'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link CursorColumn CursorLine
hi! link ColorColumn CursorLine
hi! link CurSearch IncSearch
hi! link PopupSelected PmenuSel
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character String
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1d1d1d', '#ca0a37', '#539a8e', '#ff9900', '#92919d', '#d96d4e', '#3f94cb', '#bbbdbf', '#2a2a2a', '#ff0000', '#77d1c3', '#ffe923', '#c4e90c', '#e99075', '#5dafcd', '#ffffff']
endif
if get(g:, 'metoffice_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
  hi Terminal guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
endif
hi Conceal guifg=#bbbdbf guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=#ffffff guibg=#1d1d1d gui=reverse cterm=reverse
hi CursorLine guifg=NONE guibg=#2a2a2a gui=NONE cterm=NONE
hi DiffAdd guifg=#539a8e guibg=#1d1d1d gui=reverse cterm=reverse
hi DiffChange guifg=#ffe923 guibg=#1d1d1d gui=reverse cterm=reverse
hi DiffDelete guifg=#ff0000 guibg=#1d1d1d gui=reverse cterm=reverse
hi DiffText guifg=#ff9900 guibg=#1d1d1d gui=bold,reverse cterm=bold,reverse
hi EndOfBuffer guifg=#e99075 guibg=#1d1d1d gui=NONE cterm=NONE
hi ErrorMsg guifg=#ffffff guibg=#1d1d1d gui=reverse cterm=reverse
hi Folded guifg=#bbbdbf guibg=NONE gui=italic cterm=italic
hi FoldColumn guifg=#bbbdbf guibg=#1d1d1d gui=NONE cterm=NONE
hi SignColumn guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
hi LineNr guifg=#3f94cb guibg=#2a2a2a gui=NONE cterm=NONE
hi CursorLineNr guifg=#c4e90c guibg=#2a2a2a gui=bold cterm=bold
hi MatchParen guifg=#ffe923 guibg=NONE gui=bold,reverse cterm=bold,reverse
hi ModeMsg guifg=#c4e90c guibg=#1d1d1d gui=bold cterm=bold
hi MoreMsg guifg=#539a8e guibg=#1d1d1d gui=NONE cterm=NONE
hi Question guifg=#5dafcd guibg=#1d1d1d gui=NONE cterm=NONE
hi Title guifg=#3f94cb guibg=#1d1d1d gui=bold cterm=bold
hi Directory guifg=#ff9900 guibg=#1d1d1d gui=NONE cterm=NONE
hi NonText guifg=#e99075 guibg=#1d1d1d gui=NONE cterm=NONE
hi SpecialKey guifg=#bbbdbf guibg=#1d1d1d gui=NONE cterm=NONE
hi Pmenu guifg=#ffffff guibg=#2a2a2a gui=NONE cterm=NONE
hi PmenuSbar guifg=NONE guibg=#bbbdbf gui=NONE cterm=NONE
hi PmenuSel guifg=#3f94cb guibg=#2a2a2a gui=bold cterm=bold
hi PmenuThumb guifg=NONE guibg=#bbbdbf gui=NONE cterm=NONE
hi Search guifg=#ffe923 guibg=NONE gui=NONE cterm=NONE
hi IncSearch guifg=#ffe923 guibg=NONE gui=bold cterm=bold
hi SpellBad guifg=NONE guibg=NONE guisp=#ff0000 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#ffe923 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#e99075 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#5dafcd gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi StatusLine guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
hi StatusLineNC guifg=#bbbdbf guibg=#1d1d1d gui=NONE cterm=NONE
hi TabLine guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
hi TabLineFill guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
hi TabLineSel guifg=#ffffff guibg=#1d1d1d gui=NONE cterm=NONE
hi VertSplit guifg=#ffffff guibg=#2a2a2a gui=NONE cterm=NONE
hi Visual guifg=#ffe923 guibg=#2a2a2a gui=NONE cterm=NONE
hi VisualNOS guifg=#ffe923 guibg=#2a2a2a gui=italic cterm=italic
hi WarningMsg guifg=#ca0a37 guibg=#1d1d1d gui=NONE cterm=NONE
hi WildMenu guifg=#3f94cb guibg=#1d1d1d gui=bold cterm=bold
hi Error guifg=#ca0a37 guibg=NONE gui=reverse cterm=reverse
hi Comment guifg=#bbbdbf guibg=NONE gui=italic cterm=italic
hi Todo guifg=#bbbdbf guibg=NONE gui=bold cterm=bold
hi Constant guifg=#ff9900 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#5dafcd guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#77d1c3 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#3f94cb guibg=NONE gui=italic cterm=italic
hi Function guifg=#3f94cb guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#c4e90c guibg=NONE gui=bold cterm=bold
hi Operator guifg=#ffe923 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#92919d guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#e99075 guibg=NONE gui=bold cterm=bold
hi Macro guifg=#92919d guibg=NONE gui=italic cterm=italic
hi Type guifg=#539a8e guibg=NONE gui=italic cterm=italic
hi Special guifg=#d96d4e guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=fg guibg=NONE gui=underline cterm=underline
hi Ignore guifg=#1d1d1d guibg=NONE gui=NONE cterm=NONE
hi Noise guifg=#bbbdbf guibg=NONE gui=NONE cterm=NONE
hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#1d1d1d gui=NONE cterm=NONE
hi ToolbarButton guifg=#ffffff guibg=#1d1d1d gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi VisualNOS gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
  hi Identifier gui=NONE cterm=NONE
  hi Macro gui=NONE cterm=NONE
  hi Type gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'metoffice_transp_bg', 0)
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=255 ctermbg=232 cterm=NONE
    hi Terminal ctermfg=255 ctermbg=232 cterm=NONE
  endif
  hi Conceal ctermfg=250 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=255 ctermbg=232 cterm=reverse
  hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=72 ctermbg=232 cterm=reverse
  hi DiffChange ctermfg=220 ctermbg=232 cterm=reverse
  hi DiffDelete ctermfg=196 ctermbg=232 cterm=reverse
  hi DiffText ctermfg=208 ctermbg=232 cterm=bold,reverse
  hi EndOfBuffer ctermfg=216 ctermbg=232 cterm=NONE
  hi ErrorMsg ctermfg=255 ctermbg=232 cterm=reverse
  hi Folded ctermfg=250 ctermbg=NONE cterm=italic
  hi FoldColumn ctermfg=250 ctermbg=232 cterm=NONE
  hi SignColumn ctermfg=255 ctermbg=232 cterm=NONE
  hi LineNr ctermfg=39 ctermbg=236 cterm=NONE
  hi CursorLineNr ctermfg=148 ctermbg=236 cterm=bold
  hi MatchParen ctermfg=220 ctermbg=NONE cterm=bold,reverse
  hi ModeMsg ctermfg=148 ctermbg=232 cterm=bold
  hi MoreMsg ctermfg=72 ctermbg=232 cterm=NONE
  hi Question ctermfg=74 ctermbg=232 cterm=NONE
  hi Title ctermfg=39 ctermbg=232 cterm=bold
  hi Directory ctermfg=208 ctermbg=232 cterm=NONE
  hi NonText ctermfg=216 ctermbg=232 cterm=NONE
  hi SpecialKey ctermfg=250 ctermbg=232 cterm=NONE
  hi Pmenu ctermfg=255 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=250 cterm=NONE
  hi PmenuSel ctermfg=39 ctermbg=236 cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=250 cterm=NONE
  hi Search ctermfg=220 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=220 ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=255 ctermbg=232 cterm=NONE
  hi StatusLineNC ctermfg=250 ctermbg=232 cterm=NONE
  hi TabLine ctermfg=255 ctermbg=232 cterm=NONE
  hi TabLineFill ctermfg=255 ctermbg=232 cterm=NONE
  hi TabLineSel ctermfg=255 ctermbg=232 cterm=NONE
  hi VertSplit ctermfg=255 ctermbg=236 cterm=NONE
  hi Visual ctermfg=220 ctermbg=236 cterm=NONE
  hi VisualNOS ctermfg=220 ctermbg=236 cterm=italic
  hi WarningMsg ctermfg=161 ctermbg=232 cterm=NONE
  hi WildMenu ctermfg=39 ctermbg=232 cterm=bold
  hi Error ctermfg=161 ctermbg=NONE cterm=reverse
  hi Comment ctermfg=250 ctermbg=NONE cterm=italic
  hi Todo ctermfg=250 ctermbg=NONE cterm=bold
  hi Constant ctermfg=208 ctermbg=NONE cterm=NONE
  hi String ctermfg=74 ctermbg=NONE cterm=NONE
  hi Number ctermfg=116 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=39 ctermbg=NONE cterm=italic
  hi Function ctermfg=39 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=148 ctermbg=NONE cterm=bold
  hi Operator ctermfg=220 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=246 ctermbg=NONE cterm=NONE
  hi Include ctermfg=216 ctermbg=NONE cterm=bold
  hi Macro ctermfg=246 ctermbg=NONE cterm=italic
  hi Type ctermfg=72 ctermbg=NONE cterm=italic
  hi Special ctermfg=167 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=fg ctermbg=NONE cterm=underline
  hi Ignore ctermfg=232 ctermbg=NONE cterm=NONE
  hi Noise ctermfg=250 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=232 cterm=NONE
  hi ToolbarButton ctermfg=255 ctermbg=232 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi Identifier cterm=NONE
    hi Macro cterm=NONE
    hi Type cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'metoffice_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi Conceal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=reverse
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightYellow ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=LightRed ctermbg=Black cterm=reverse
  hi DiffText ctermfg=DarkYellow ctermbg=Black cterm=bold,reverse
  hi EndOfBuffer ctermfg=LightMagenta ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=White ctermbg=Black cterm=reverse
  hi Folded ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
  hi LineNr ctermfg=DarkCyan ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=LightBlue ctermbg=DarkGrey cterm=bold
  hi MatchParen ctermfg=LightYellow ctermbg=NONE cterm=bold,reverse
  hi ModeMsg ctermfg=LightBlue ctermbg=Black cterm=bold
  hi MoreMsg ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi Question ctermfg=LightCyan ctermbg=Black cterm=NONE
  hi Title ctermfg=DarkCyan ctermbg=Black cterm=bold
  hi Directory ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightMagenta ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=DarkCyan ctermbg=DarkGrey cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi Search ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=LightYellow ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=White ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi Visual ctermfg=LightYellow ctermbg=DarkGrey cterm=NONE
  hi VisualNOS ctermfg=LightYellow ctermbg=DarkGrey cterm=italic
  hi WarningMsg ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=DarkCyan ctermbg=Black cterm=bold
  hi Error ctermfg=DarkRed ctermbg=NONE cterm=reverse
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Todo ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi String ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi Number ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=italic
  hi Function ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightBlue ctermbg=NONE cterm=bold
  hi Operator ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Include ctermfg=LightMagenta ctermbg=NONE cterm=bold
  hi Macro ctermfg=DarkBlue ctermbg=NONE cterm=italic
  hi Type ctermfg=DarkGreen ctermbg=NONE cterm=italic
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=fg ctermbg=NONE cterm=underline
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi Noise ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi Identifier cterm=NONE
    hi Macro cterm=NONE
    hi Type cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black       #1d1d1d   232       Black
" Color: dgrey       #2a2a2a   236       DarkGrey
" Color: lgrey       #bbbdbf   250       LightGrey
" Color: white       #ffffff   255       White
" Color: red         #ff0000   196       LightRed
" Color: rwarn       #ca0a37   161       DarkRed
" Color: awarn       #ff9900   208       DarkYellow
" Color: ywarn       #ffe923   220       LightYellow
" Color: lspring     #77d1c3   116       LightGreen
" Color: spring      #539a8e   72        DarkGreen
" Color: lsummer     #5dafcd   74        LightCyan
" Color: summer      #3f94cb   39        DarkCyan
" Color: core        #c4e90c   148       LightBlue
" Color: winter      #92919d   246       DarkBlue
" Color: autumn      #d96d4e   167       DarkMagenta
" Color: lautumn     #e99075   216       LightMagenta
" Term colors: black rwarn spring awarn
" Term colors: winter autumn summer lgrey
" Term colors: dgrey red lspring ywarn
" Term colors: core lautumn lsummer white
" vim: et ts=2 sw=2
